---
- name: Set full FQDN var
  set_fact:
     fqdn: "{{ hostname }}.{{ domain }}"
  tags:
    - always

- name: Create server Razor tag
  shell: "/usr/local/bin/razor create-tag --name {{ hostname }} --rule '[\"in\", [\"fact\", \"serialnumber\"],\"{{ hostvars[hostname]['serial_number'] }}\"]'"
  tags:
    - create_tag

- name: Create server Razor policy json file
  template:
    src: templates/razor_policy.json.j2
    dest: "{{ hostname }}.json"
  tags:
    - create_policy

- name: Create server Razor policy
  shell: "/usr/local/bin/razor create-policy --json {{ hostname }}.json"
  tags:
    - create_policy

- name: Remove server Razor policy json file
  file:
    path: "{{ hostname }}.json"
    state: absent
  tags:
    - create_policy
